version: 2
jobs:

  linter:
    working_directory: ~/Mobile
    docker:
      - image: circleci/node:10.9
    steps:
      - checkout

      - restore_cache:
          name: Restore Cache (yarn)
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          name: Restore Cache (node_modules)
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn

      - save_cache:
          name: Save Cache (yarn)
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          name: Save Cache (node_modules)
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run: yarn lint

workflows:
  version: 2
  gitflow-linter:
    jobs:
      - linter
